<table width="200px;">
<tr>
	<td>ID</td><td>用户名</td><td>密码</td>
</tr>
<?php foreach($admin as $val): ?>
	<tr>
		<td><?php echo $this->escapeHtml($val->ad_id);?></td>
		<td><?php echo $this->escapeHtml($val->ad_name);?></td>
		<td><?php echo $this->escapeHtml($val->ad_password);?></td>
	</tr>
	
<?php endforeach; ?>
</table>
<li class="active"><a href="/Hwi/Index/add"><?php echo $this->translate('登录') ?></a></li>
